name: CI/CD Pipeline for DevOps Project 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0 

      # Set CI to false to prevent warnings from being treated as errors
      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      # Install dependencies and build the frontend
      - name: Install and Build Frontend
        working-directory: client
        run: |
          npm install
          npm run build

      # Move frontend build files to backend public folder
      - name: Move Build to Backend Public Folder
        run: cp -r client/build/* public/

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js version 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0  

      # Install dependencies (including dev dependencies like jest)
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH key to connect to EC2 (use the new key without passphrase)
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # La clave SSH sin passphrase

      # Copy project to EC2 server
      - name: Deploy to EC2
        run: |
          ssh ec2-user@54.85.23.194 "rm -rf ~/PetAdoptionDevOps/*"
          scp -r . ec2-user@54.85.23.194:~/PetAdoptionDevOps/

      # Restart the application on EC2
      - name: Restart Application on EC2
        run: |
          ssh ec2-user@54.85.23.194 << 'EOF'
          cd ~/PetAdoptionDevOps
          npm install
          pm2 stop all || true
          pm2 start index.js --name "devops-app"
          EOF
